# CI/CD Workflow for Building Java Microservices and creating Docker Image of them.

name: BuildCode

# Controls when the workflow will run
on:
  # Triggers the workflow on call from the source repo.
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
    outputs:
      imageName:
        description: "Image name with Tag"
        value: ${{ jobs.build.outputs.imageName }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    outputs:
      imageName: ${{ steps.build-image.outputs.imageName }}

    steps:

    - name: Run a one-line script
      run: echo Hello, world! ${{ inputs.serviceName }}
        
    - name: Build Output
      id: build-image
      env:
        IMAGE_TAG: ThisIsJobOutput
      run: echo "::set-output name=imageName::$IMAGE_TAG"
